# Generated by Django 5.1 on 2024-09-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
