# Generated by Django 5.1 on 2024-09-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_category_alter_post_miniature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="miniature",
            field=models.ImageField(blank=True, null=True, upload_to="posts_images/"),
        ),
    ]
